//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_deposit
    {
        public int Account_id { get; set; }
        public int Deposite_type_id { get; set; }
        public System.DateTime Opening_date { get; set; }
        public System.DateTime Expiry_date { get; set; }
    
        public virtual bank_account bank_account { get; set; }
        public virtual deposite_type deposite_type { get; set; }
    }
}
