//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public int id { get; set; }
        public string User_login { get; set; }
        public int Credit_type_id { get; set; }
        public DateTime Opening_date { get; set; }
        public DateTime Expiry_date { get; set; }
        public Nullable<double> Paid_sum { get; set; }
    
        public virtual credit_type credit_type { get; set; }
        public virtual user user { get; set; }
    }
}
