//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_of_user
    {
        public string User_login { get; set; }
        public string Passport_series { get; set; }
        public string Passport_number { get; set; }
    
        public virtual user user { get; set; }
    }
}
