//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bank_systemEntities : DbContext
    {
        public bank_systemEntities()
            : base("name=bank_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank_account> bank_account { get; set; }
        public virtual DbSet<bank_deposit> bank_deposit { get; set; }
        public virtual DbSet<credit> credit { get; set; }
        public virtual DbSet<credit_type> credit_type { get; set; }
        public virtual DbSet<data_of_user> data_of_user { get; set; }
        public virtual DbSet<deposite_type> deposite_type { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
